const GOOGLE_API_KEY = process.env.REACT_APP_GOOGLE_API_KEY;

export const LIVE_CHAT_COUNT = 25;

export const YOUTUBE_VIDEOS_API =process.env.REACT_APP_YOUTUBE_VIDEOS_API+GOOGLE_API_KEY;

export const YOUTUBE_SEARCH_API = process.env.REACT_APP_YOUTUBE_SEARCH_API